perl6:
	perl6 -Ilib bin/p6g2idea generate perl6.pm6 ../../src/edument/perl6idea/parsing/ Perl6 edument.rakuidea.parsing

crotmp:
	perl6 -Ilib bin/p6g2idea generate crotmp.pm6 ../../src/edument/perl6idea/cro/template/parsing CroTemplate edument.rakuidea.cro.template.parsing
